// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuJ7IuYl5c4RCztgE2jX15m6uV-BkQm-I',
    appId: '1:746786174247:web:5dac79a95974f7f34ae502',
    messagingSenderId: '746786174247',
    projectId: 'archalyzer-5b35c',
    authDomain: 'archalyzer-5b35c.firebaseapp.com',
    storageBucket: 'archalyzer-5b35c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNRsdzWLgJuOs6_hx0zr9agQCBkJyjU0M',
    appId: '1:746786174247:android:a7346422b5a4142c4ae502',
    messagingSenderId: '746786174247',
    projectId: 'archalyzer-5b35c',
    storageBucket: 'archalyzer-5b35c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfy5smXF3wIMtznJ7ROzfbiHuc01s-iWU',
    appId: '1:746786174247:ios:ef77187c261cf4944ae502',
    messagingSenderId: '746786174247',
    projectId: 'archalyzer-5b35c',
    storageBucket: 'archalyzer-5b35c.firebasestorage.app',
    iosBundleId: 'com.rigon.archalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuJ7IuYl5c4RCztgE2jX15m6uV-BkQm-I',
    appId: '1:746786174247:web:6a0bbfc86511803f4ae502',
    messagingSenderId: '746786174247',
    projectId: 'archalyzer-5b35c',
    authDomain: 'archalyzer-5b35c.firebaseapp.com',
    storageBucket: 'archalyzer-5b35c.firebasestorage.app',
  );

}