name: archalyzer
description: "Archalyzer Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  image_picker: ^1.1.2
  get_it: ^7.7.0
  intl: ^0.20.2
  uuid: ^3.0.7
  flutter_dotenv: ^5.0.2
  dio: ^5.9.0
  font_awesome_flutter: ^10.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
